name: CI (Work)

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  build:
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir $HOME/.dotfiles
          mv * $HOME/.dotfiles
          ls -al $HOME
      - name: Run the install
        run: |
          sh $HOME/.dotfiles/install-work.sh
