name: Continuous Integration

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  build:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
        with:
          path: $HOME/.dotfiles
      - name: Run the install
        run: sh $HOME/.dotfiles/work/install.sh
