name: Continuous Integration

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  build:
    runs-on: macOS-11
    steps:
      - run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Run the install
        run: |
          pwd
